//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounts()
        {
            this.AccJournalDtl = new HashSet<AccJournalDtl>();
            this.Accounts1 = new HashSet<Accounts>();
            this.Accounts11 = new HashSet<Accounts>();
            this.AccountsBudget = new HashSet<AccountsBudget>();
            this.AccountsCCD = new HashSet<AccountsCCD>();
            this.ExpensesRequestsDtl = new HashSet<ExpensesRequestsDtl>();
            this.PayablesAccDtl = new HashSet<PayablesAccDtl>();
            this.PayablesHdr = new HashSet<PayablesHdr>();
            this.PmtApproveAccDtl = new HashSet<PmtApproveAccDtl>();
            this.ReceivablesAccDtl = new HashSet<ReceivablesAccDtl>();
        }
    
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string BranchCode { get; set; }
        public string TypeCode { get; set; }
        public int AccLevel { get; set; }
        public string ParentAccCode { get; set; }
        public int IsFinal { get; set; }
        public int SubAccType { get; set; }
        public string CurrencyCode { get; set; }
        public int FinalStatement { get; set; }
        public string ClosingAccCode { get; set; }
        public Nullable<int> BankNum { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccJournalDtl> AccJournalDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts> Accounts1 { get; set; }
        public virtual Accounts Accounts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accounts> Accounts11 { get; set; }
        public virtual Accounts Accounts3 { get; set; }
        public virtual AccTypes AccTypes { get; set; }
        public virtual BranchCodes BranchCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsBudget> AccountsBudget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsCCD> AccountsCCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesRequestsDtl> ExpensesRequestsDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayablesAccDtl> PayablesAccDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayablesHdr> PayablesHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmtApproveAccDtl> PmtApproveAccDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivablesAccDtl> ReceivablesAccDtl { get; set; }
    }
}
