//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountsCCD
    {
        public string CenterCode { get; set; }
        public string AccCode { get; set; }
        public double DistributionRatio { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual CostCenters CostCenters { get; set; }
    }
}
