//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__FrmPmtPASSource
    {
        public string PASNum { get; set; }
        public System.DateTime PASDate { get; set; }
        public string PersonCode { get; set; }
        public string Payee { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public double AmountCurr { get; set; }
        public Nullable<int> BankNum { get; set; }
        public string BankName { get; set; }
        public string Notes { get; set; }
        public string DocNum { get; set; }
    }
}
