//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__POTransHdr
    {
        public string DocNum { get; set; }
        public System.DateTime DocDate { get; set; }
        public string BranchCode { get; set; }
        public string OrderNum { get; set; }
        public int IsPosted { get; set; }
        public string Notes { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
    }
}
