//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__PurchaseOrderQutDtl
    {
        public string ID { get; set; }
        public string OrderNum { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public Nullable<double> OrderedQty { get; set; }
        public string Memo { get; set; }
        public string PQUT_ID { get; set; }
        public string PO_ID { get; set; }
    
        public virtual PurchaseOrderHdr PurchaseOrderHdr { get; set; }
    }
}
