//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCentersBudget
    {
        public string CenterCode { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
    }
}
