//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostingDtl
    {
        public string ID { get; set; }
        public string EntryNum { get; set; }
        public string CostCode { get; set; }
        public double Value { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string Trn_ID { get; set; }
        public string ItemCode { get; set; }
        public string Notes { get; set; }
    
        public virtual CostItems CostItems { get; set; }
        public virtual CostingHdr CostingHdr { get; set; }
    }
}
