//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic
    {
        public string FieldName { get; set; }
        public string LatinCap { get; set; }
        public string ArabicCap { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<byte> Align { get; set; }
    }
}
