//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastByMonth
    {
        public string BranchCode { get; set; }
        public int Y { get; set; }
        public int M { get; set; }
        public Nullable<double> ForecastAmount { get; set; }
    }
}
