//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourSeasons
    {
        public int ObjectID { get; set; }
        public string ObjectName { get; set; }
        public string ObjectTitle { get; set; }
        public byte[] Icon { get; set; }
    }
}
