//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glossary
    {
        public string EngTerm { get; set; }
        public string ArbTerm { get; set; }
        public int Ignore { get; set; }
        public string Source { get; set; }
    }
}
