//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsRelated
    {
        public string ItemCode { get; set; }
        public string ItemCodeRelated { get; set; }
        public int RelatedType { get; set; }
    
        public virtual ItemsDirectory ItemsDirectory { get; set; }
        public virtual ItemsDirectory ItemsDirectory1 { get; set; }
    }
}
