//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsDirectory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemsDirectory()
        {
            this.ItemRequestDtl = new HashSet<ItemRequestDtl>();
            this.Items = new HashSet<Items>();
            this.ItemSerials = new HashSet<ItemSerials>();
            this.ItemsInOutL = new HashSet<ItemsInOutL>();
            this.ItemsRelated = new HashSet<ItemsRelated>();
            this.ItemsRelated1 = new HashSet<ItemsRelated>();
            this.ReservationDtl = new HashSet<ReservationDtl>();
            this.ServiceOrderDtl = new HashSet<ServiceOrderDtl>();
            this.ServiceOrderHdr = new HashSet<ServiceOrderHdr>();
        }
    
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string AltrItemName { get; set; }
        public string PartNumber { get; set; }
        public int ItemType { get; set; }
        public string Cat1Code { get; set; }
        public string Cat2Code { get; set; }
        public string Cat3Code { get; set; }
        public string Cat4Code { get; set; }
        public string GroupID { get; set; }
        public int CostMethod { get; set; }
        public double Cost { get; set; }
        public int Serialized { get; set; }
        public int Expired { get; set; }
        public int Active { get; set; }
        public int Discontinued { get; set; }
        public int Salable { get; set; }
        public double PurPrice { get; set; }
        public double SalPrice1 { get; set; }
        public double SalPrice2 { get; set; }
        public double SalPrice3 { get; set; }
        public double SalPrice4 { get; set; }
        public double SalPrice5 { get; set; }
        public double SalPrice { get; set; }
        public Nullable<double> MinSalPrice { get; set; }
        public string VendCode { get; set; }
        public string ManufacturerCode { get; set; }
        public string ClassID { get; set; }
        public string Notes { get; set; }
        public string OldItemCode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<System.DateTime> PriceDateModified { get; set; }
        public string LongDescription { get; set; }
        public string MPGCode { get; set; }
        public Nullable<System.DateTime> VendorPriceDate1 { get; set; }
        public Nullable<System.DateTime> VendorPriceDate2 { get; set; }
        public Nullable<System.DateTime> VendorPriceDate3 { get; set; }
        public Nullable<double> VendorPrice1 { get; set; }
        public Nullable<double> VendorPrice2 { get; set; }
        public Nullable<double> VendorPrice3 { get; set; }
        public int HSCode { get; set; }
        public int MOQ { get; set; }
        public string CurrencyCode { get; set; }
        public string Status { get; set; }
        public string PricesModifiedBy { get; set; }
    
        public virtual Currencies Currencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestDtl> ItemRequestDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        public virtual ItemsMPG ItemsMPG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSerials> ItemSerials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInOutL> ItemsInOutL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsRelated> ItemsRelated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsRelated> ItemsRelated1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationDtl> ReservationDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderDtl> ServiceOrderDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderHdr> ServiceOrderHdr { get; set; }
    }
}
