//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInOutExp
    {
        public string ID { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string PatchNum { get; set; }
        public double Qty { get; set; }
    
        public virtual ItemsInOutL ItemsInOutL { get; set; }
    }
}
