//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInOutH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemsInOutH()
        {
            this.ItemsInOutL = new HashSet<ItemsInOutL>();
        }
    
        public string Serial { get; set; }
        public string BranchCode { get; set; }
        public int DocNum { get; set; }
        public int TransType { get; set; }
        public string TransNum { get; set; }
        public string TransCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string StoreCode { get; set; }
        public string DestBranchCode { get; set; }
        public string MTN { get; set; }
        public string PersonCode { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string TContactCode { get; set; }
        public string TTerms { get; set; }
        public Nullable<int> TIsCredit { get; set; }
        public Nullable<double> TAmount { get; set; }
        public Nullable<double> TTotCommission { get; set; }
        public string CenterCode { get; set; }
        public string Notes { get; set; }
        public string DeliveredBy { get; set; }
        public string ReceivedBy { get; set; }
        public System.DateTime TransTime { get; set; }
        public int IsPosted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
    
        public virtual InvTransTypes InvTransTypes { get; set; }
        public virtual Stores Stores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsInOutL> ItemsInOutL { get; set; }
        public virtual CostingHdr CostingHdr { get; set; }
    }
}
