//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequestHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemRequestHdr()
        {
            this.ItemRequestDtl = new HashSet<ItemRequestDtl>();
        }
    
        public string RequestNum { get; set; }
        public int BrnSerial { get; set; }
        public string ServerCode { get; set; }
        public string BranchCode { get; set; }
        public string RequestFrom { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestedBy { get; set; }
        public string Attention { get; set; }
        public string AttentionCC { get; set; }
        public string RequiredOn { get; set; }
        public int Status { get; set; }
        public int Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Notes { get; set; }
        public int IsPosted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestDtl> ItemRequestDtl { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
