//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsClasses
    {
        public string ClassID { get; set; }
        public string ItemClass { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<int> Shipping { get; set; }
        public double Customs { get; set; }
        public double Insurance { get; set; }
        public double Handling { get; set; }
        public double Marketing { get; set; }
        public double Commissions { get; set; }
        public double Markup { get; set; }
        public double DealerRate { get; set; }
        public double RoundingOff { get; set; }
        public double RoundingOffRetail { get; set; }
        public double ShippingRate { get; set; }
    }
}
