//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobileV
    {
        public string Serial { get; set; }
        public string Expr1 { get; set; }
        public string SerialNum { get; set; }
        public string ID { get; set; }
        public string BranchCode { get; set; }
    }
}
