//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NonStockItems
    {
        public string ItemCode { get; set; }
        public Nullable<double> P_O { get; set; }
        public Nullable<double> Purchases { get; set; }
        public Nullable<double> PUR_Trans { get; set; }
    }
}
