//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenPIitems
    {
        public string ItemCode { get; set; }
        public double InvQty { get; set; }
        public Nullable<double> RcvQty { get; set; }
        public int Shipped { get; set; }
        public string StoreCode { get; set; }
        public string BranchCode { get; set; }
    }
}
