//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.AccJournalDtl = new HashSet<AccJournalDtl>();
            this.ExpensesRequestsHdr = new HashSet<ExpensesRequestsHdr>();
            this.ItemRequestHdr = new HashSet<ItemRequestHdr>();
            this.PayablesHdr = new HashSet<PayablesHdr>();
            this.PmtApproveHdr = new HashSet<PmtApproveHdr>();
            this.PurAcknowledgementsHdr = new HashSet<PurAcknowledgementsHdr>();
            this.PurchaseHdr = new HashSet<PurchaseHdr>();
            this.PurchaseHdr1 = new HashSet<PurchaseHdr>();
            this.PurchaseOrderHdr = new HashSet<PurchaseOrderHdr>();
            this.PurchaseOrderHdr1 = new HashSet<PurchaseOrderHdr>();
            this.PORequestHdr = new HashSet<PORequestHdr>();
            this.PORequestHdr1 = new HashSet<PORequestHdr>();
            this.PurchaseReturnHdr = new HashSet<PurchaseReturnHdr>();
            this.PurchaseReturnHdr1 = new HashSet<PurchaseReturnHdr>();
            this.ScmSalesMen = new HashSet<ScmSalesMen>();
            this.SalesHdr = new HashSet<SalesHdr>();
            this.SalesHdr1 = new HashSet<SalesHdr>();
            this.SalesOrderHdr = new HashSet<SalesOrderHdr>();
            this.SalesOrderHdr1 = new HashSet<SalesOrderHdr>();
            this.SalesReturnHdr = new HashSet<SalesReturnHdr>();
            this.SalesReturnHdr1 = new HashSet<SalesReturnHdr>();
            this.SalQuotationsHdr = new HashSet<SalQuotationsHdr>();
            this.SalQuotationsHdr1 = new HashSet<SalQuotationsHdr>();
            this.ScmRatiosHdr = new HashSet<ScmRatiosHdr>();
            this.ServiceOrderHdr = new HashSet<ServiceOrderHdr>();
            this.ServiceOrderHdr1 = new HashSet<ServiceOrderHdr>();
        }
    
        public string PersonCode { get; set; }
        public int PersonType { get; set; }
        public string PersonName { get; set; }
        public string PersonAltrName { get; set; }
        public string BranchCode { get; set; }
        public string CurrencyCode { get; set; }
        public string AccCode { get; set; }
        public string OurAccountNum { get; set; }
        public string CenterCode { get; set; }
        public int CategoryCode { get; set; }
        public int NonTrade { get; set; }
        public string PersonGroupID { get; set; }
        public string PersonSubGroupID { get; set; }
        public string ContactCode { get; set; }
        public double CreditLimit { get; set; }
        public string PmtTerms { get; set; }
        public int Rank { get; set; }
        public string UserName { get; set; }
        public string E_Mail { get; set; }
        public string URL { get; set; }
        public int Active { get; set; }
        public string Address { get; set; }
        public string ShipAddress { get; set; }
        public string PoBox { get; set; }
        public string ShipPoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string ShipFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string ShipPhone { get; set; }
        public string ShipAltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string ShipTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
        public string TradeLicenseNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccJournalDtl> AccJournalDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpensesRequestsHdr> ExpensesRequestsHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestHdr> ItemRequestHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayablesHdr> PayablesHdr { get; set; }
        public virtual PersonsGroups PersonsGroups { get; set; }
        public virtual PersonsGroupsDtl PersonsGroupsDtl { get; set; }
        public virtual PersonTypes PersonTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmtApproveHdr> PmtApproveHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurAcknowledgementsHdr> PurAcknowledgementsHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseHdr> PurchaseHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseHdr> PurchaseHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderHdr> PurchaseOrderHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderHdr> PurchaseOrderHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequestHdr> PORequestHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORequestHdr> PORequestHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnHdr> PurchaseReturnHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseReturnHdr> PurchaseReturnHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScmSalesMen> ScmSalesMen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesHdr> SalesHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesHdr> SalesHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderHdr> SalesOrderHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderHdr> SalesOrderHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturnHdr> SalesReturnHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturnHdr> SalesReturnHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalQuotationsHdr> SalQuotationsHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalQuotationsHdr> SalQuotationsHdr1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScmRatiosHdr> ScmRatiosHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderHdr> ServiceOrderHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderHdr> ServiceOrderHdr1 { get; set; }
    }
}
