//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonsRequests
    {
        public string RequestNum { get; set; }
        public int BrnSerial { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestedBy { get; set; }
        public int Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public int IsPosted { get; set; }
        public string PersonCode { get; set; }
        public int PersonType { get; set; }
        public string PersonName { get; set; }
        public string PersonAltrName { get; set; }
        public string BranchCode { get; set; }
        public int CategoryCode { get; set; }
        public string PersonGroupID { get; set; }
        public string PersonSubGroupID { get; set; }
        public double CreditLimit { get; set; }
        public string PmtTerms { get; set; }
        public string Address { get; set; }
        public string PoBox { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string E_Mail { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
        public int IsAddition { get; set; }
        public string TradeLicenseNo { get; set; }
        public string AltrPhone { get; set; }
        public string CenterCode { get; set; }
        public int Active { get; set; }
    
        public virtual CostCenters CostCenters { get; set; }
        public virtual PersonsGroups PersonsGroups { get; set; }
        public virtual PersonsGroupsDtl PersonsGroupsDtl { get; set; }
    }
}
