//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderHdr()
        {
            this.C__PurchaseOrderQutDtl = new HashSet<C__PurchaseOrderQutDtl>();
            this.PurchaseOrderDtl = new HashSet<PurchaseOrderDtl>();
        }
    
        public string OrderNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public string ServerCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string VendCode { get; set; }
        public string BuyerCode { get; set; }
        public string Terms { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string ShipperCode { get; set; }
        public string ShipReqDate { get; set; }
        public Nullable<int> DeliveryOrder { get; set; }
        public int Canceled { get; set; }
        public int Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Address { get; set; }
        public string ShipAddress { get; set; }
        public string SupAddress { get; set; }
        public string PoBox { get; set; }
        public string ShipPoBox { get; set; }
        public string SupPoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string ShipFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string SupFax { get; set; }
        public string SupAltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string ShipPhone { get; set; }
        public string ShipAltrPhone { get; set; }
        public string SupPhone { get; set; }
        public string SupAltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string ShipTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string SupTelx { get; set; }
        public string SupAltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public string FollowUpMan { get; set; }
        public string Notes { get; set; }
        public string Instructions { get; set; }
        public int IsPosted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C__PurchaseOrderQutDtl> C__PurchaseOrderQutDtl { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual Persons Persons { get; set; }
        public virtual Persons Persons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtl> PurchaseOrderDtl { get; set; }
        public virtual PurShippers PurShippers { get; set; }
        public virtual Terms Terms1 { get; set; }
    }
}
