//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderDtl()
        {
            this.PurAcknowledgementsDtl = new HashSet<PurAcknowledgementsDtl>();
            this.PurchaseDtl = new HashSet<PurchaseDtl>();
        }
    
        public string ID { get; set; }
        public string OrderNum { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public Nullable<double> OrderedQty { get; set; }
        public string Memo { get; set; }
        public Nullable<double> OnHndQty { get; set; }
        public Nullable<double> InTransit { get; set; }
        public Nullable<double> BO { get; set; }
        public Nullable<double> LastPrice { get; set; }
        public string Quot_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurAcknowledgementsDtl> PurAcknowledgementsDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDtl> PurchaseDtl { get; set; }
        public virtual PurchaseOrderHdr PurchaseOrderHdr { get; set; }
    }
}
