//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurQuotationsHdr
    {
        public string QuotNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public string ServerCode { get; set; }
        public System.DateTime QuotDate { get; set; }
        public string VendCode { get; set; }
        public string BuyerCode { get; set; }
        public string RequestedBy { get; set; }
        public string Terms { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public int Status { get; set; }
        public int Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string Instructions { get; set; }
        public int IsPosted { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string Contact { get; set; }
        public string QuotationNum { get; set; }
        public string IndirectCustomerName { get; set; }
        public string FinalCustomerName { get; set; }
    }
}
