//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurShipmentsHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurShipmentsHdr()
        {
            this.PurShipmentsDtl = new HashSet<PurShipmentsDtl>();
            this.PurShipmentsInv = new HashSet<PurShipmentsInv>();
        }
    
        public string ShipNum { get; set; }
        public string ShipperRefNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime ShipDate { get; set; }
        public string ShipperCode { get; set; }
        public int ShipMethodCode { get; set; }
        public int Shipped { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Volume { get; set; }
        public string Palette { get; set; }
        public Nullable<int> ContainersNO { get; set; }
        public Nullable<int> PiecesNO { get; set; }
        public string MBL { get; set; }
        public string HBL { get; set; }
        public Nullable<System.DateTime> ETS { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ATS { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string Vessel_Airline { get; set; }
        public string VoyageNum { get; set; }
        public string VoyageDetails { get; set; }
        public string BrokerCode { get; set; }
        public Nullable<System.DateTime> DocsRcvDate { get; set; }
        public Nullable<System.DateTime> DateCleared { get; set; }
        public string Address { get; set; }
        public string PoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public string URL { get; set; }
        public string ShipAddress { get; set; }
        public string ShipPoBox { get; set; }
        public string ShipFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string ShipAltrPhone { get; set; }
        public string ShipTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string BrkAddress { get; set; }
        public string BrkPoBox { get; set; }
        public string BrkFax { get; set; }
        public string BrkAltrFax { get; set; }
        public string BrkPhone { get; set; }
        public string ShipPhone { get; set; }
        public string BrkAltrPhone { get; set; }
        public string BrkTelx { get; set; }
        public string BrkAltrTelx { get; set; }
        public string BrkContact { get; set; }
        public string BrkContactTitle { get; set; }
        public string BrkOthContact { get; set; }
        public string BrkOthContactTitle { get; set; }
        public string BrkE_Mail { get; set; }
        public int IsPosted { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurShipmentsDtl> PurShipmentsDtl { get; set; }
        public virtual ShipMethods ShipMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurShipmentsInv> PurShipmentsInv { get; set; }
    }
}
