//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivablesInvDtl
    {
        public string DocNum { get; set; }
        public string SaleNum { get; set; }
        public double Paid { get; set; }
    
        public virtual ReceivablesHdr ReceivablesHdr { get; set; }
        public virtual SalesHdr SalesHdr { get; set; }
    }
}
