//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepItemsList
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string Cat1Code { get; set; }
        public string Cat2Code { get; set; }
        public string Cat3Code { get; set; }
        public string Cat4Code { get; set; }
        public string Cat1Name { get; set; }
        public string Cat2Name { get; set; }
        public string Cat3Name { get; set; }
        public string Cat4Name { get; set; }
        public double SalPrice1 { get; set; }
        public double SalPrice2 { get; set; }
        public double SalPrice3 { get; set; }
        public double SalPrice4 { get; set; }
        public double SalPrice5 { get; set; }
        public double SalPrice { get; set; }
    }
}
