//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepSalesByCategories
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string Cat1Code { get; set; }
        public string Cat1Name { get; set; }
        public string Cat2Code { get; set; }
        public string Cat2Name { get; set; }
        public string Cat3Code { get; set; }
        public string Cat3Name { get; set; }
        public string Cat4Code { get; set; }
        public string Cat4Name { get; set; }
        public string ManufacturerCode { get; set; }
        public string Manufacturer { get; set; }
        public double Sales { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime SaleDate { get; set; }
    }
}
