//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesHdr()
        {
            this.ReceivablesInvDtl = new HashSet<ReceivablesInvDtl>();
            this.SalesDtl = new HashSet<SalesDtl>();
            this.SalesReturnHdr = new HashSet<SalesReturnHdr>();
            this.ServiceOrderHdr = new HashSet<ServiceOrderHdr>();
        }
    
        public string SaleNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Service { get; set; }
        public string CustCode { get; set; }
        public int IsCredit { get; set; }
        public string SalesMan { get; set; }
        public string OrderNum { get; set; }
        public string Terms { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string CenterCode { get; set; }
        public int SpecialCommission { get; set; }
        public double TotCommission { get; set; }
        public string Address { get; set; }
        public string PoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public int Closed { get; set; }
        public int IsPosted { get; set; }
        public string TransCode { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual Persons Persons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivablesInvDtl> ReceivablesInvDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDtl> SalesDtl { get; set; }
        public virtual Terms Terms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturnHdr> SalesReturnHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOrderHdr> ServiceOrderHdr { get; set; }
    }
}
