//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDiscDtl
    {
        public string Disc_ID { get; set; }
        public string Sal_ID { get; set; }
        public double DiscQty { get; set; }
        public double DiscPrice { get; set; }
        public string TransCode { get; set; }
        public string Memo { get; set; }
    
        public virtual SalesDtl SalesDtl { get; set; }
    }
}
