//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesByMonth
    {
        public string BranchCode { get; set; }
        public Nullable<int> SaleYear { get; set; }
        public Nullable<int> SaleMonth { get; set; }
        public Nullable<double> SaleAmount { get; set; }
    }
}
