//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesDtl()
        {
            this.SalesDiscDtl = new HashSet<SalesDiscDtl>();
            this.SalesReturnDtl = new HashSet<SalesReturnDtl>();
        }
    
        public string ID { get; set; }
        public string Ord_ID { get; set; }
        public string SaleNum { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public Nullable<double> Commission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesDiscDtl> SalesDiscDtl { get; set; }
        public virtual SalesHdr SalesHdr { get; set; }
        public virtual SalesOrderDtl SalesOrderDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesReturnDtl> SalesReturnDtl { get; set; }
    }
}
