//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalQuotationsDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalQuotationsDtl()
        {
            this.SalesOrderDtl = new HashSet<SalesOrderDtl>();
        }
    
        public string ID { get; set; }
        public string QuotNum { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double UnitPrice { get; set; }
        public double Price { get; set; }
        public int Delivery { get; set; }
        public double Discount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderDtl> SalesOrderDtl { get; set; }
        public virtual SalQuotationsHdr SalQuotationsHdr { get; set; }
    }
}
