//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScmRatiosDtl
    {
        public string RateNum { get; set; }
        public string GroupID { get; set; }
        public string ItemCode { get; set; }
        public string CustGroupID { get; set; }
        public double CreditComm { get; set; }
        public double CashComm { get; set; }
        public string IsRatio { get; set; }
    
        public virtual ItemsGroups ItemsGroups { get; set; }
        public virtual PersonsGroups PersonsGroups { get; set; }
        public virtual ScmRatiosHdr ScmRatiosHdr { get; set; }
    }
}
