//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScmSalesMen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScmSalesMen()
        {
            this.ScmQuota = new HashSet<ScmQuota>();
        }
    
        public string EntryNum { get; set; }
        public string BranchCode { get; set; }
        public string ServerCode { get; set; }
        public int BrnSerial { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string PeriodCode { get; set; }
        public string SalesMan { get; set; }
        public bool AsManager { get; set; }
        public double TotQuota { get; set; }
        public string Manager { get; set; }
        public double CollRatio1 { get; set; }
        public double CollPmtRatio1 { get; set; }
        public double CollRatio2 { get; set; }
        public double CollPmtRatio2 { get; set; }
        public double CollRatio3 { get; set; }
        public double CollPmtRatio3 { get; set; }
        public double CollRatio4 { get; set; }
        public double CollPmtRatio4 { get; set; }
        public double CollRatio5 { get; set; }
        public double CollPmtRatio5 { get; set; }
        public double QuotaRatio1 { get; set; }
        public double QuotaPmtRatio1 { get; set; }
        public double QuotaPmtBonus1 { get; set; }
        public double QuotaRatio2 { get; set; }
        public double QuotaPmtRatio2 { get; set; }
        public double QuotaPmtBonus2 { get; set; }
        public double QuotaRatio3 { get; set; }
        public double QuotaPmtRatio3 { get; set; }
        public double QuotaPmtBonus3 { get; set; }
        public double QuotaRatio4 { get; set; }
        public double QuotaPmtRatio4 { get; set; }
        public double QuotaPmtBonus4 { get; set; }
        public double QuotaRatio5 { get; set; }
        public double QuotaPmtRatio5 { get; set; }
        public double QuotaPmtBonus5 { get; set; }
        public int IsPosted { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
    
        public virtual Persons Persons { get; set; }
        public virtual ScmPeriods ScmPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScmQuota> ScmQuota { get; set; }
    }
}
