//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3539354544443837
    {
        public string Terms { get; set; }
        public int CreditFor { get; set; }
        public double Prepayment { get; set; }
        public double CashOnDelivery { get; set; }
        public string Notes { get; set; }
    }
}
