//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x4631413631364339
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string BranchManager { get; set; }
        public int ObjectID { get; set; }
        public bool SerialNumberValidation { get; set; }
        public string Acc_PaperImport { get; set; }
        public string Acc_PaperExport { get; set; }
        public string Acc_RetPaperImport { get; set; }
        public string Acc_RetPaperExport { get; set; }
        public string Acc_Bank { get; set; }
        public string Acc_Chq { get; set; }
        public string Acc_BankExp { get; set; }
        public string Acc_BankInc { get; set; }
        public string Acc_LostMony { get; set; }
        public string Acc_CurrencyDiff { get; set; }
        public string Acc_Cash { get; set; }
        public string Acc_Sal { get; set; }
        public string Acc_SalRet { get; set; }
        public string Acc_Pur { get; set; }
        public string Acc_AR { get; set; }
        public string Acc_AP { get; set; }
        public string Acc_PurRet { get; set; }
        public string Acc_COGS { get; set; }
        public string Acc_Employees { get; set; }
        public string Acc_Others { get; set; }
        public string Acc_Close { get; set; }
        public string DefTerms { get; set; }
        public string DefSalesMan { get; set; }
        public string DefDeliveryMethodCode { get; set; }
        public string DefStoreCode { get; set; }
        public string DefShipMethodCode { get; set; }
        public string DefServiceTypeCode { get; set; }
        public string DefBuyer { get; set; }
        public string DefTech { get; set; }
        public string DefClass { get; set; }
        public Nullable<int> PrvMinSalPrice { get; set; }
        public Nullable<int> PrvCreditLimit { get; set; }
        public Nullable<int> CalCost { get; set; }
        public string Address { get; set; }
        public string ShipAddress { get; set; }
        public string PoBox { get; set; }
        public string ShipPoBox { get; set; }
        public string Fax { get; set; }
        public string ShipFax { get; set; }
        public string AltrFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string Phone { get; set; }
        public string ShipPhone { get; set; }
        public string AltrPhone { get; set; }
        public string ShipAltrPhone { get; set; }
        public string Telx { get; set; }
        public string ShipTelx { get; set; }
        public string AltrTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
    }
}
