//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3633464344424334
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public int ItemType { get; set; }
        public string Cat1Code { get; set; }
        public string Cat2Code { get; set; }
        public string Cat3Code { get; set; }
        public string Cat4Code { get; set; }
        public int CostMethod { get; set; }
        public double Cost { get; set; }
        public int Serialized { get; set; }
        public int Expired { get; set; }
        public double PurPrice { get; set; }
        public double SalPrice1 { get; set; }
        public double SalPrice2 { get; set; }
        public double SalPrice3 { get; set; }
        public double SalPrice4 { get; set; }
        public double SalPrice5 { get; set; }
        public double SalPrice { get; set; }
        public double MinSalPrice { get; set; }
        public string VendCode { get; set; }
        public string ManufacturerCode { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Salable { get; set; }
        public string OldItemCode { get; set; }
    }
}
