//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3337373339393438
    {
        public string CenterCode { get; set; }
        public string CenterName { get; set; }
        public string CenterParent { get; set; }
        public int CenterLevel { get; set; }
        public int CenterIsFinal { get; set; }
        public string IssuedBy { get; set; }
    }
}
