//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class syncobj_0x3742394242333936
    {
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string BranchCode { get; set; }
        public string TypeCode { get; set; }
        public int AccLevel { get; set; }
        public string ParentAccCode { get; set; }
        public int IsFinal { get; set; }
        public int SubAccType { get; set; }
        public string CurrencyCode { get; set; }
        public int FinalStatement { get; set; }
        public string ClosingAccCode { get; set; }
        public string Notes { get; set; }
        public string IssuedBy { get; set; }
        public string OldCode { get; set; }
    }
}
