//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class System
    {
        public string BranchCode { get; set; }
        public string CompanyName { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<int> BeginYear { get; set; }
        public Nullable<int> TransCount { get; set; }
        public bool GLEntriesForMTN { get; set; }
        public Nullable<bool> UseSales { get; set; }
        public Nullable<bool> UsePurchs { get; set; }
        public Nullable<bool> UseStocks { get; set; }
        public Nullable<bool> UseBanks { get; set; }
        public Nullable<bool> UseAccounts { get; set; }
        public Nullable<bool> UseNotifications { get; set; }
        public string ServerCode { get; set; }
    }
}
