//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmSalesReturn
    {
        public string RetNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime RetDate { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public int IsCredit { get; set; }
        public string SalesMan { get; set; }
        public string SaleNum { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public string CenterCode { get; set; }
        public string CenterName { get; set; }
        public string Notes { get; set; }
        public string IssuedBy { get; set; }
    }
}
