//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmSalesReturnSS_Lines1ItemCodeRowSource
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public double Price { get; set; }
        public double SoldQty { get; set; }
        public Nullable<double> Issued { get; set; }
        public Nullable<double> Returned { get; set; }
        public string ID { get; set; }
        public int ItemType { get; set; }
        public string PartNumber { get; set; }
    }
}
