//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmSalOpenQuots
    {
        public string ItemCode { get; set; }
        public string PartNumber { get; set; }
        public string ItemName { get; set; }
        public double Qty { get; set; }
        public Nullable<double> OrderedQty { get; set; }
        public Nullable<double> OnHndQty { get; set; }
        public string QuotNum { get; set; }
        public System.DateTime QuotDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public string SalesMan { get; set; }
        public string Notes { get; set; }
    }
}
