//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmLinkInventorySales
    {
        public string SaleNum { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string SalesMan { get; set; }
        public string OrderNum { get; set; }
        public string CustCode { get; set; }
        public double ChangeRate { get; set; }
        public string CurrencyCode { get; set; }
        public string PersonName { get; set; }
    }
}
