//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmSalesReturnSS_DbcSaleNumValidatePmt
    {
        public string DocNum { get; set; }
        public System.DateTime DocDate { get; set; }
        public double Paid { get; set; }
        public Nullable<double> Discount { get; set; }
        public string SaleNum { get; set; }
        public string PersonCode { get; set; }
    }
}
