//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmJournalSS_LinesRowSource
    {
        public double DebitCurr { get; set; }
        public double CreditCurr { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public Nullable<double> CostCenters { get; set; }
        public string Memo { get; set; }
        public string ID { get; set; }
    }
}
