//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmSalesOrders
    {
        public string OrderNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public string SalesMan { get; set; }
        public string PurOrder { get; set; }
        public string Terms { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public int DeliveryOrder { get; set; }
        public string DeliveryMethodCode { get; set; }
        public string DeliveryMethod { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Address { get; set; }
        public string ShipAddress { get; set; }
        public string PoBox { get; set; }
        public string ShipPoBox { get; set; }
        public string Fax { get; set; }
        public string ShipFax { get; set; }
        public string AltrFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string Phone { get; set; }
        public string ShipPhone { get; set; }
        public string AltrPhone { get; set; }
        public string ShipAltrPhone { get; set; }
        public string Telx { get; set; }
        public string ShipTelx { get; set; }
        public string AltrTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public int Canceled { get; set; }
        public int IsPosted { get; set; }
        public string Notes { get; set; }
        public string IssuedBy { get; set; }
    }
}
