//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmReceivablesSS_Lines2
    {
        public double Value { get; set; }
        public string AccID { get; set; }
        public string AccName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public Nullable<double> TotClasses { get; set; }
        public string Memo { get; set; }
        public string ID { get; set; }
    }
}
