//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpFrmEmployees
    {
        public string PersonCode { get; set; }
        public int PersonType { get; set; }
        public string PersonName { get; set; }
        public string BranchCode { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public int CategoryCode { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string PoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string E_Mail { get; set; }
        public string Notes { get; set; }
    }
}
