//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpPmtList
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string DocNum { get; set; }
        public string CurrencyName { get; set; }
        public int PayMethod { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string Method { get; set; }
        public double Amount { get; set; }
        public string PersonCode { get; set; }
        public string Payee { get; set; }
        public string PersonName { get; set; }
        public System.DateTime DocDate { get; set; }
        public string ChqNum { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<System.DateTime> ChqCollectedDate { get; set; }
        public string BankName { get; set; }
        public string Serial { get; set; }
    }
}
