//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemsProfit
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Sales { get; set; }
        public Nullable<double> Costs { get; set; }
    }
}
