//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepAdjSerials
    {
        public string Serial { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public int DocNum { get; set; }
        public int TransType { get; set; }
        public string TransNum { get; set; }
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public System.DateTime TransDate { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string DestBranchCode { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string Notes { get; set; }
        public string DeliveredBy { get; set; }
        public string ReceivedBy { get; set; }
        public int IsPosted { get; set; }
        public string IssuedBy { get; set; }
        public string ID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public double Qty { get; set; }
        public string SerialNum { get; set; }
    }
}
