//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepAccountTB
    {
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string TypeCode { get; set; }
        public int AccLevel { get; set; }
        public string ParentAccCode { get; set; }
        public int IsFinal { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public Nullable<double> DL { get; set; }
        public Nullable<double> CL { get; set; }
        public int BDL { get; set; }
        public int BCL { get; set; }
    }
}
