//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepCollectionForecast
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string Description { get; set; }
        public string SaleNum { get; set; }
        public double Amount { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> ForecastAmount { get; set; }
        public int DebitAmount { get; set; }
        public int CollectedAmount { get; set; }
        public double ChangeRate { get; set; }
    }
}
