//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPersonsTBTrans
    {
        public string PersonCode { get; set; }
        public int PersonType { get; set; }
        public string PersonName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public System.DateTime TransDate { get; set; }
        public double DF { get; set; }
        public double CF { get; set; }
        public double DL { get; set; }
        public double CL { get; set; }
        public int BDF { get; set; }
        public int BCF { get; set; }
        public int BDL { get; set; }
        public int BCL { get; set; }
    }
}
