//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSrvOrdersDetails
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string SaleNum { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string SerialNum { get; set; }
        public string CustCode { get; set; }
        public string CustName { get; set; }
        public Nullable<System.DateTime> PromiseDate { get; set; }
        public string ServiceMan { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string Problem { get; set; }
        public string TechAction { get; set; }
        public string Comments { get; set; }
        public string ServiceTypeCode { get; set; }
        public string ServiceType { get; set; }
        public string Notes { get; set; }
        public int Canceled { get; set; }
        public string SpareCode { get; set; }
        public Nullable<double> Qty { get; set; }
        public string SpareName { get; set; }
        public string SparePartNumber { get; set; }
    }
}
