//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalOutStandingInvoicesBal
    {
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<double> Bal { get; set; }
        public Nullable<double> BalL { get; set; }
        public Nullable<double> DueBal { get; set; }
        public Nullable<double> DueBalL { get; set; }
        public string Address { get; set; }
        public string PoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public double CreditLimit { get; set; }
    }
}
