//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalCustSerials
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string TransNum { get; set; }
        public System.DateTime TransDate { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string ID { get; set; }
        public string SerialNum { get; set; }
    }
}
