//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPurDeliveryDetails
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string PurNum { get; set; }
        public System.DateTime PurDate { get; set; }
        public string VendCode { get; set; }
        public string PersonName { get; set; }
        public string BuyerCode { get; set; }
        public string InvNum { get; set; }
        public string Terms { get; set; }
        public int Closed { get; set; }
        public int Shipped { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ShipMethodCode { get; set; }
        public string ShipMethod { get; set; }
        public string ShipReqDate { get; set; }
        public string Memo { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Received { get; set; }
    }
}
