//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemsOpenMTN
    {
        public string Serial { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime TransDate { get; set; }
        public string StoreCode { get; set; }
        public string DestBranchCode { get; set; }
        public string Notes { get; set; }
        public string BranchName { get; set; }
        public string StoreName { get; set; }
        public string DestBranchName { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> MTNQty { get; set; }
        public Nullable<double> MrnQty { get; set; }
        public string MTN { get; set; }
        public string MrnSerial { get; set; }
        public Nullable<System.DateTime> MrnDate { get; set; }
    }
}
