//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepInvoice
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string SaleNum { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public string PoBox { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string Contact { get; set; }
        public string SalesMan { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PurOrder { get; set; }
        public string Terms { get; set; }
        public double Amount { get; set; }
        public string CurrencyName { get; set; }
        public string Notes { get; set; }
        public string IssuedBy { get; set; }
        public string ID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public string SerialNum { get; set; }
        public string CustName { get; set; }
    }
}
