//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalATBCollFCRet
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string ContactCode { get; set; }
        public double CreditLimit { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
