//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPersonsTBBegBal
    {
        public string PersonCode { get; set; }
        public int PersonType { get; set; }
        public string PersonName { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public System.DateTime TransDate { get; set; }
        public int DF { get; set; }
        public int CF { get; set; }
        public int DL { get; set; }
        public int CL { get; set; }
        public double BDF { get; set; }
        public double BCF { get; set; }
        public double BDL { get; set; }
        public double bCL { get; set; }
    }
}
