//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalCollectionDelay
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public double CreditLimit { get; set; }
        public int Rank { get; set; }
        public string SaleNum { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int IsCredit { get; set; }
        public string SalesMan { get; set; }
        public string OrderNum { get; set; }
        public string Terms { get; set; }
        public int CreditFor { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public double Amount { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<double> Paid { get; set; }
    }
}
