//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemCardByCost
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string Serial { get; set; }
        public int DocNum { get; set; }
        public string TransNum { get; set; }
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public int TransType { get; set; }
        public System.DateTime TransDate { get; set; }
        public System.DateTime TransTime { get; set; }
        public string Notes { get; set; }
        public double Qty { get; set; }
        public double Cost { get; set; }
    }
}
