//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemTransSummaryBal
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string BranchCode { get; set; }
        public string PartNumber { get; set; }
        public string Cat4Code { get; set; }
        public string Cat4Name { get; set; }
        public Nullable<double> Qty { get; set; }
        public string StoreCode { get; set; }
        public string ManufacturerCode { get; set; }
        public string Cat3Code { get; set; }
        public string Cat3Name { get; set; }
        public string Cat2Code { get; set; }
        public string Cat2Name { get; set; }
        public string Cat1Code { get; set; }
        public string Cat1Name { get; set; }
        public int CRET { get; set; }
        public int MRN { get; set; }
        public int MTN { get; set; }
        public int SAL5 { get; set; }
        public int SAL4 { get; set; }
        public int SAL3 { get; set; }
        public int SAL2 { get; set; }
        public int SAL1 { get; set; }
    }
}
