//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPurchaseOrderForm
    {
        public string BranchCode { get; set; }
        public string BranchManager { get; set; }
        public int BrnSerial { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string VendCode { get; set; }
        public string PersonName { get; set; }
        public string BuyerCode { get; set; }
        public string Buyer { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public string ShipMethodCode { get; set; }
        public string ShipMethod { get; set; }
        public string ViaAddress { get; set; }
        public string ViaPoBox { get; set; }
        public string ViaFax { get; set; }
        public string ViaAltrFax { get; set; }
        public string ViaPhone { get; set; }
        public string ViaAltrPhone { get; set; }
        public string ViaTelx { get; set; }
        public string ViaAltrTelx { get; set; }
        public string ViaContact { get; set; }
        public string ViaContactTitle { get; set; }
        public string ViaOthContact { get; set; }
        public string ViaOthContactTitle { get; set; }
        public string ViaE_Mail { get; set; }
        public string Terms { get; set; }
        public string ShipReqDate { get; set; }
        public Nullable<int> DeliveryOrder { get; set; }
        public int Canceled { get; set; }
        public string Address { get; set; }
        public string ShipAddress { get; set; }
        public string SupAddress { get; set; }
        public string PoBox { get; set; }
        public string ShipPoBox { get; set; }
        public string SupPoBox { get; set; }
        public string Fax { get; set; }
        public string AltrFax { get; set; }
        public string ShipFax { get; set; }
        public string ShipAltrFax { get; set; }
        public string SupFax { get; set; }
        public string SupAltrFax { get; set; }
        public string Phone { get; set; }
        public string AltrPhone { get; set; }
        public string ShipPhone { get; set; }
        public string ShipAltrPhone { get; set; }
        public string SupPhone { get; set; }
        public string SupAltrPhone { get; set; }
        public string Telx { get; set; }
        public string AltrTelx { get; set; }
        public string ShipTelx { get; set; }
        public string ShipAltrTelx { get; set; }
        public string SupTelx { get; set; }
        public string SupAltrTelx { get; set; }
        public string Contact { get; set; }
        public string ContactTitle { get; set; }
        public string OthContact { get; set; }
        public string OthContactTitle { get; set; }
        public string E_Mail { get; set; }
        public string FollowUpMan { get; set; }
        public string OurAccountNum { get; set; }
        public string Notes { get; set; }
        public string ID { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string Memo { get; set; }
    }
}
