//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepCompanyStatusVRET
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string TCode { get; set; }
        public string TName { get; set; }
        public int PmtMethod { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
