//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepCCStatment
    {
        public string CenterKey { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CenterCode { get; set; }
        public string CenterName { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string CurrencyName { get; set; }
        public string Serial { get; set; }
        public int BrnSerial { get; set; }
        public string TransNum { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public double DF { get; set; }
        public double CF { get; set; }
        public string Memo { get; set; }
    }
}
