//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemsCostSumExp
    {
        public string EntryNum { get; set; }
        public string CostCode { get; set; }
        public string CostName { get; set; }
        public Nullable<double> ExpF { get; set; }
        public Nullable<double> Exp { get; set; }
    }
}
