//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepWarrantyClaim
    {
        public System.DateTime OrderDate { get; set; }
        public string CustName { get; set; }
        public string SerialNum { get; set; }
        public string Problem { get; set; }
        public string SalesMan { get; set; }
        public string Tech { get; set; }
        public string OrderNum { get; set; }
        public string SaleNum { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string SparePart { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> Qty { get; set; }
    }
}
