//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPurOrdersDetails
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string VendCode { get; set; }
        public string PersonName { get; set; }
        public string BuyerCode { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public string Terms { get; set; }
        public string ShipReqDate { get; set; }
        public int Canceled { get; set; }
        public string ID { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string PurNum { get; set; }
    }
}
