//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalesmenCommissions
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string SaleNum { get; set; }
        public string SalesMan { get; set; }
        public string ItemGroup { get; set; }
        public string PersonGroup { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<double> SubTotal { get; set; }
        public Nullable<double> Commission { get; set; }
        public string PeriodCode { get; set; }
        public string PeriodDescription { get; set; }
        public Nullable<double> Quota { get; set; }
        public Nullable<double> TotQuota { get; set; }
        public Nullable<double> CollRatio1 { get; set; }
        public Nullable<double> CollPmtRatio1 { get; set; }
        public Nullable<double> CollRatio2 { get; set; }
        public Nullable<double> CollPmtRatio2 { get; set; }
        public Nullable<double> CollRatio3 { get; set; }
        public Nullable<double> CollPmtRatio3 { get; set; }
        public Nullable<double> CollRatio4 { get; set; }
        public Nullable<double> CollPmtRatio4 { get; set; }
        public Nullable<double> CollRatio5 { get; set; }
        public Nullable<double> CollPmtRatio5 { get; set; }
        public Nullable<double> QuotaRatio1 { get; set; }
        public Nullable<double> QuotaPmtRatio1 { get; set; }
        public Nullable<double> QuotaPmtBonus1 { get; set; }
        public Nullable<double> QuotaRatio2 { get; set; }
        public Nullable<double> QuotaPmtRatio2 { get; set; }
        public Nullable<double> QuotaPmtBonus2 { get; set; }
        public Nullable<double> QuotaRatio3 { get; set; }
        public Nullable<double> QuotaPmtRatio3 { get; set; }
        public Nullable<double> QuotaPmtBonus3 { get; set; }
        public Nullable<double> QuotaRatio4 { get; set; }
        public Nullable<double> QuotaPmtRatio4 { get; set; }
        public Nullable<double> QuotaPmtBonus4 { get; set; }
        public Nullable<double> QuotaRatio5 { get; set; }
        public Nullable<double> QuotaPmtRatio5 { get; set; }
        public Nullable<double> QuotaPmtBonus5 { get; set; }
        public string TNum { get; set; }
    }
}
