//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemsCostSheet
    {
        public string EntryNum { get; set; }
        public int BrnSerial { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int Purchases { get; set; }
        public string Notes { get; set; }
        public string VchNum { get; set; }
        public string TransNum { get; set; }
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public int TransType { get; set; }
        public System.DateTime TransDate { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public double Cost { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public string PurNum { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public string InvNum { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string MemoOrder { get; set; }
        public string MemoInvoice { get; set; }
    }
}
