//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepAccTransSummary
    {
        public string BranchCode { get; set; }
        public string AccCode { get; set; }
        public string AccName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public int BrnSerial { get; set; }
        public string Serial { get; set; }
        public string TransNum { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public string Notes { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string CurrencyName { get; set; }
        public double DebitCurr { get; set; }
        public double CreditCurr { get; set; }
        public double Debit { get; set; }
        public double Credit { get; set; }
        public string Memo { get; set; }
    }
}
