//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemCostSummary
    {
        public string VchID { get; set; }
        public string ItemCode { get; set; }
        public double Qty { get; set; }
        public Nullable<double> PriceL { get; set; }
        public double Cost { get; set; }
        public string CostID { get; set; }
        public string CostCode { get; set; }
        public Nullable<double> ValueL { get; set; }
        public string Trn_ID { get; set; }
        public string ExpItemCode { get; set; }
        public string EntryNum { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string CostName { get; set; }
        public int AffectPrice { get; set; }
        public string CostType { get; set; }
        public string ShipType { get; set; }
    }
}
