//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepSalesBackOrders
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public string SalesMan { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public double Qty { get; set; }
        public Nullable<double> Issued { get; set; }
        public string Notes { get; set; }
    }
}
