//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemsTrialBalByCostBeg
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public int Cost { get; set; }
        public Nullable<double> BegCost { get; set; }
        public int TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
