//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepPmtVoucher
    {
        public string DocNum { get; set; }
        public string Serial { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string ExtLetter { get; set; }
        public System.DateTime DocDate { get; set; }
        public int Expenses { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
        public string Payee { get; set; }
        public string CurrencyCodeP { get; set; }
        public string CurrencyNameP { get; set; }
        public string AccCode { get; set; }
        public int PayMethod { get; set; }
        public string Method { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public double ChangeRate { get; set; }
        public double AmountCurr { get; set; }
        public string ChqNum { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public Nullable<int> BankNum { get; set; }
        public string BankName { get; set; }
        public int Collected { get; set; }
        public Nullable<System.DateTime> ChqCollectedDate { get; set; }
        public string CenterCode { get; set; }
        public string Notes { get; set; }
        public int IsPosted { get; set; }
        public string TransCode { get; set; }
        public string IssuedBy { get; set; }
        public string SerialGL { get; set; }
        public string ID { get; set; }
        public string AccCodeL { get; set; }
        public string AccNameL { get; set; }
        public string PersonCodeL { get; set; }
        public string PersonNameL { get; set; }
        public string CurrencyCodeL { get; set; }
        public string CurrencyNameL { get; set; }
        public double ChangeRateL { get; set; }
        public double DebitCurr { get; set; }
        public double Debit { get; set; }
        public double CreditCurr { get; set; }
        public double Credit { get; set; }
        public string Memo { get; set; }
        public string CenterCodeL { get; set; }
        public string CenterName { get; set; }
        public Nullable<double> ValueCurr { get; set; }
    }
}
