//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepItemSerialHistory
    {
        public string Serial { get; set; }
        public string SerialNum { get; set; }
        public System.DateTime TransDate { get; set; }
        public string TransName { get; set; }
        public string TransNum { get; set; }
        public int DocNum { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string StoreCode { get; set; }
        public string ItemCode { get; set; }
        public string PartNumber { get; set; }
        public string ItemName { get; set; }
        public string PersonCode { get; set; }
        public string PersonName { get; set; }
    }
}
