//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpRepCreditSalesRatio
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int IsCredit { get; set; }
        public Nullable<double> SalesAmount { get; set; }
    }
}
