//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Um_AlQura
    {
        public short HY { get; set; }
        public Nullable<byte> M1 { get; set; }
        public Nullable<byte> M2 { get; set; }
        public Nullable<byte> M3 { get; set; }
        public Nullable<byte> M4 { get; set; }
        public Nullable<byte> M5 { get; set; }
        public Nullable<byte> M6 { get; set; }
        public Nullable<byte> M7 { get; set; }
        public Nullable<byte> M8 { get; set; }
        public Nullable<byte> M9 { get; set; }
        public Nullable<byte> M10 { get; set; }
        public Nullable<byte> M11 { get; set; }
        public Nullable<byte> M12 { get; set; }
        public Nullable<System.DateTime> GS { get; set; }
        public Nullable<short> RefID { get; set; }
    }
}
