//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRights
    {
        public string UserName { get; set; }
        public int ObjectID { get; set; }
        public string BranchCode { get; set; }
        public bool CanRun { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public bool CanPrint { get; set; }
        public bool CanBrows { get; set; }
        public Nullable<bool> AllBranches { get; set; }
        public string ServerCode { get; set; }
        public Nullable<System.DateTime> AccessDate { get; set; }
    
        public virtual Objects Objects { get; set; }
        public virtual Users Users { get; set; }
    }
}
