//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersRecent
    {
        public int ObjectID { get; set; }
        public string UserName { get; set; }
        public string Criteria { get; set; }
        public System.DateTime AccessDate { get; set; }
    }
}
