//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW8
    {
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string CustCode { get; set; }
        public string PersonName { get; set; }
        public string Salesman { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public System.DateTime MonthDate { get; set; }
        public System.DateTime QDate { get; set; }
        public string Q { get; set; }
        public int M { get; set; }
        public int Y { get; set; }
        public double Qty { get; set; }
        public double Price { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> BO { get; set; }
        public Nullable<double> Transit { get; set; }
        public double LMSales { get; set; }
    }
}
