//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW9
    {
        public string ItemGroupID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> TransitQty { get; set; }
        public Nullable<double> BOQty { get; set; }
        public Nullable<double> LMSales { get; set; }
        public double Price { get; set; }
        public int M1 { get; set; }
        public int M2 { get; set; }
        public int M3 { get; set; }
    }
}
