//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW1
    {
        public System.DateTime OrderDate { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Cat4Code { get; set; }
        public string Cat4Name { get; set; }
        public Nullable<double> Qty { get; set; }
        public string PType { get; set; }
    }
}
