//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW4
    {
        public string ItemCode { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> TransitQty { get; set; }
        public Nullable<double> BOQty { get; set; }
        public Nullable<double> LMSales { get; set; }
        public double SalPrice1 { get; set; }
    }
}
