//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW12
    {
        public string BranchCode { get; set; }
        public string ItemCode { get; set; }
        public string Q { get; set; }
        public double Balance { get; set; }
        public double BOQty { get; set; }
        public double TransitQty { get; set; }
    }
}
