//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSerials
    {
        public string ID { get; set; }
        public string Serial { get; set; }
        public string TransCode { get; set; }
        public string TransNum { get; set; }
        public System.DateTime TransDate { get; set; }
        public int DocNum { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string SerialNum { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string Trn_ID { get; set; }
        public string DISC_ID { get; set; }
    
        public virtual ItemsDirectory ItemsDirectory { get; set; }
        public virtual ItemsInOutL ItemsInOutL { get; set; }
    }
}
