//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIS_2019.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JEDMISDBEntities : DbContext
    {
        public JEDMISDBEntities()
            : base("name=JEDMISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvTransTypes> InvTransTypes { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemsDirectory> ItemsDirectory { get; set; }
        public virtual DbSet<ItemSerials> ItemSerials { get; set; }
        public virtual DbSet<ItemsInOutH> ItemsInOutH { get; set; }
        public virtual DbSet<ItemsInOutL> ItemsInOutL { get; set; }
        public virtual DbSet<Objects> Objects { get; set; }
        public virtual DbSet<ObjectsDtl> ObjectsDtl { get; set; }
        public virtual DbSet<UserRights> UserRights { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<string> SP_Mainmnu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Mainmnu");
        }
    
        public virtual ObjectResult<string> SP_SubMnu(string mnuname)
        {
            var mnunameParameter = mnuname != null ?
                new ObjectParameter("mnuname", mnuname) :
                new ObjectParameter("mnuname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_SubMnu", mnunameParameter);
        }
    }
}
