//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using global::System;
        using global::System.Collections.Generic;
    
    public partial class InvTransTypes
    {

        public InvTransTypes()
        {
            this.ItemsInOutH = new HashSet<ItemsInOutH>();
        }
    
        public string TransCode { get; set; }
        public string TransName { get; set; }
        public int TransType { get; set; }
        public int System { get; set; }
        public int TOrder { get; set; }
        public string Notes { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public string IssuedBy { get; set; }
    
 
        public virtual ICollection<ItemsInOutH> ItemsInOutH { get; set; }
    }
}
