//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using global::System;
        using global::System.Collections.Generic;
    
    public partial class ItemsGroups
    {
        public string GroupID { get; set; }
        public string ItemGroup { get; set; }
        public string Notes { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public string IssuedBy { get; set; }
    }
}
