//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using global::System;
        using global::System.Collections.Generic;
    
    public partial class ItemsInOutH
    {

        public ItemsInOutH()
        {
            this.ItemsInOutL = new HashSet<ItemsInOutL>();
        }
    
        public string Serial { get; set; }
        public string BranchCode { get; set; }
        public int DocNum { get; set; }
        public int TransType { get; set; }
        public string TransNum { get; set; }
        public string TransCode { get; set; }
        public string TransDate { get; set; }
        public string StoreCode { get; set; }
        public string DestBranchCode { get; set; }
        public string MTN { get; set; }
        public string PersonCode { get; set; }
        public string CurrencyCode { get; set; }
        public double ChangeRate { get; set; }
        public string TContactCode { get; set; }
        public string TTerms { get; set; }
        public Nullable<int> TIsCredit { get; set; }
        public Nullable<double> TAmount { get; set; }
        public Nullable<double> TTotCommission { get; set; }
        public string CenterCode { get; set; }
        public string Notes { get; set; }
        public string DeliveredBy { get; set; }
        public string ReceivedBy { get; set; }
        public string TransTime { get; set; }
        public int IsPosted { get; set; }
        public string DateCreated { get; set; }
        public string DateModified { get; set; }
        public string IssuedBy { get; set; }
        public string ServerCode { get; set; }
    
        public virtual InvTransTypes InvTransTypes { get; set; }
 
        public virtual ICollection<ItemsInOutL> ItemsInOutL { get; set; }
    }
}
