//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using global::System;
        using global::System.Collections.Generic;
    
    public partial class ObjectsDtl
    {
        public int ObjectID { get; set; }
        public string CriteriaFields { get; set; }
        public string CriteriaFieldsTables { get; set; }
        public string CriteriaFieldsSources { get; set; }
        public string CriteriaFieldsBoundColumn { get; set; }
        public string CriteriaFieldsTypes { get; set; }
        public string CriteriaFieldsCaptions { get; set; }
        public string CriteriaFieldsAlignments { get; set; }
        public string CriteriaFieldsWidths { get; set; }
        public string CriteriaFieldsOperators { get; set; }
        public string CriteriaFieldsUnique { get; set; }
        public string CFSourcesByBranch { get; set; }
        public string SortFieldsList { get; set; }
    }
}
