move itmbycat.rpt WithoutSqlNext
move itemlist.rpt WithoutSqlNext
rem move adjseril.rpt WithoutSqlNext
rem move adj.rpt WithoutSqlNext
move ibalbcat.rpt WithoutSqlNext
move scustitm.rpt WithoutSqlNext
move rcvreg.rpt WithoutSqlNext
move poitems.rpt WithoutSqlNext
move VendList.rpt WithoutSqlNext
move custlist.rpt WithoutSqlNext
move rcvlist.rpt WithoutSqlNext
move pmtlist.rpt WithoutSqlNext
move salsumry.rpt WithoutSqlNext
move saldetil.rpt WithoutSqlNext
move salitmsu.rpt WithoutSqlNext
move sbkorder.rpt WithoutSqlNext
move priclist.rpt WithoutSqlNext
move purordsu.rpt WithoutSqlNext
move purordde.rpt WithoutSqlNext
move salordde.rpt WithoutSqlNext
move Salordsu.rpt WithoutSqlNext
move SalDlvde.rpt WithoutSqlNext
move Category.rpt WithoutSqlNext
move salitmtt.rpt WithoutSqlNext
move accjrnl.rpt WithoutSqlNext
move accchart.rpt WithoutSqlNext
move collperf.rpt WithoutSqlNext
move wntyclim.rpt WithoutSqlNext
move forecast.rpt WithoutSqlNext
move itmsrlde.rpt WithoutSqlNext
move purdetil.rpt WithoutSqlNext
move pursumry.rpt WithoutSqlNext
move srvorddt.rpt WithoutSqlNext
move srvordsm.rpt WithoutSqlNext
move itmreord.rpt WithoutSqlNext
move trgtrtio.rpt WithoutSqlNext
move devratio.rpt WithoutSqlNext
move Crdtrtio.rpt WithoutSqlNext
move ClctFcst.rpt WithoutSqlNext
move puritmde.rpt WithoutSqlNext
move salreg.rpt WithoutSqlNext
move custrnsu.rpt WithoutSqlNext
move acctrnsu.rpt WithoutSqlNext
move rsvdtl.rpt WithoutSqlNext
move rsvsum.rpt WithoutSqlNext
move cctrlbdg.rpt WithoutSqlNext
move Budget.rpt WithoutSqlNext
move CCBdgt.rpt WithoutSqlNext
move accbdg.rpt WithoutSqlNext
move ccDev.rpt WithoutSqlNext
move AccDev.rpt WithoutSqlNext
move itemprof.rpt WithoutSqlNext
move scustsrl.rpt WithoutSqlNext
move salbycat.rpt WithoutSqlNext
move itmopmtn.rpt WithoutSqlNext
move purdlvde.rpt WithoutSqlNext
move adjcost.rpt WithoutSqlNext
move salretde.rpt WithoutSqlNext
move salretsu.rpt WithoutSqlNext
move jrnldtl.rpt WithoutSqlNext
move PurRetSu.rpt WithoutSqlNext
move Purretde.rpt WithoutSqlNext
move Payreg.rpt WithoutSqlNext
move poopen.rpt WithoutSqlNext
move smnbymth.rpt WithoutSqlNext
move sabrnint.rpt WithoutSqlNext
move icosbcat.rpt WithoutSqlNext
move sacoldly.rpt WithoutSqlNext
move srvorder.rpt WithoutSqlNext
move srvordPP.rpt WithoutSqlNext
move poitmdt.rpt WithoutSqlNext
move acsumint.rpt WithoutSqlNext
move custbals.rpt WithoutSqlNext
move SalBayan.rpt WithoutSqlNext
pause